-- Seed 60+ startkaarten voor FocusPlay
insert into public.challenges (id, type, theme, content, visibility)
values
  (uuid_generate_v4(), 'fact', 'general', '{"fact":"Je brein verbruikt ongeveer 20% van je energie in rust."}', 'global'),
  (uuid_generate_v4(), 'fact', 'general', '{"fact":"Een powernap van 20 minuten maakt je direct alerter."}', 'global'),
  (uuid_generate_v4(), 'fact', 'general', '{"fact":"Lachen kan je stresshormonen tijdelijk met zo’n 40% verlagen."}', 'global'),
  (uuid_generate_v4(), 'fact', 'general', '{"fact":"Handgeschreven notities helpen details beter te onthouden."}', 'global'),
  (uuid_generate_v4(), 'fact', 'general', '{"fact":"Een koude douche van 30 seconden geeft vaak een stemmingboost."}', 'global'),
  (uuid_generate_v4(), 'fact', 'general', '{"fact":"Je werkgeheugen houdt gemiddeld zeven items vast; cluster slim."}', 'global'),
  (uuid_generate_v4(), 'fact', 'sports', '{"fact":"Toptennisers visualiseren elke rally voor betere uitvoering."}', 'global'),
  (uuid_generate_v4(), 'fact', 'sports', '{"fact":"Rustdagen bouwen spierkracht op net zo hard als trainingen."}', 'global'),
  (uuid_generate_v4(), 'fact', 'sports', '{"fact":"Sprintjes van 10 seconden verhogen je VO2 max merkbaar."}', 'global'),
  (uuid_generate_v4(), 'fact', 'sports', '{"fact":"Vijf minuten warming-up verkleint het blessurerisico fors."}', 'global'),
  (uuid_generate_v4(), 'fact', 'sports', '{"fact":"2% minder hydratatie kan je sprinttijd voelbaar vertragen."}', 'global'),
  (uuid_generate_v4(), 'fact', 'sports', '{"fact":"Krachttraining maakt teamsporters ook wendbaarder op het veld."}', 'global'),
  (uuid_generate_v4(), 'fact', 'gaming', '{"fact":"Speedrunners oefenen micro-secties tot ze spierengeheugen worden."}', 'global'),
  (uuid_generate_v4(), 'fact', 'gaming', '{"fact":"Korte callouts in voice chat verhogen je winrate in shooters."}', 'global'),
  (uuid_generate_v4(), 'fact', 'gaming', '{"fact":"Een 144Hz-monitor vermindert motion blur en inputlag merkbaar."}', 'global'),
  (uuid_generate_v4(), 'fact', 'gaming', '{"fact":"Strategiegames scherpen besluitvorming onder tijdsdruk."}', 'global'),
  (uuid_generate_v4(), 'fact', 'gaming', '{"fact":"VR-games trainen je evenwichtsgevoel en core stabiliteit."}', 'global'),
  (uuid_generate_v4(), 'fact', 'gaming', '{"fact":"Elke 45 minuten pauze houden houdt je APM fris en nauwkeurig."}', 'global'),
  (uuid_generate_v4(), 'fact', 'productivity', '{"fact":"Batch je e-mail en bespaar gemiddeld twintig minuten per dag."}', 'global'),
  (uuid_generate_v4(), 'fact', 'productivity', '{"fact":"Twee uur staand werken per dag verhoogt je energiegevoel."}', 'global'),
  (uuid_generate_v4(), 'fact', 'productivity', '{"fact":"Het 52/17-ritme houdt je cognitieve brandstof op peil."}', 'global'),
  (uuid_generate_v4(), 'fact', 'productivity', '{"fact":"Sluit je werkdag af met een top-3 lijst en slaap rustiger."}', 'global'),
  (uuid_generate_v4(), 'fact', 'productivity', '{"fact":"Verveling triggert vaak creativiteit; plan bewust lege blokken."}', 'global'),
  (uuid_generate_v4(), 'fact', 'productivity', '{"fact":"Microbreaks van 30 seconden verminderen RSI-klachten merkbaar."}', 'global'),
  (uuid_generate_v4(), 'quiz', 'general', '{"question":"Wat is de hoofdstad van IJsland?","options":["Oslo","Reykjavik","Helsinki","Kopenhagen"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'general', '{"question":"Welke kleur krijg je door blauw en geel te mengen?","options":["Paars","Groen","Oranje","Rood"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'general', '{"question":"Hoeveel graden heeft een volledige cirkel?","options":["90","180","270","360"],"answerIndex":3}', 'global'),
  (uuid_generate_v4(), 'quiz', 'general', '{"question":"Welke planeet noemen we de rode planeet?","options":["Mars","Venus","Jupiter","Mercurius"],"answerIndex":0}', 'global'),
  (uuid_generate_v4(), 'quiz', 'general', '{"question":"Wat is het chemisch symbool voor goud?","options":["Ag","Au","Fe","Pt"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'sports', '{"question":"Hoeveel spelers heeft één voetbalteam tegelijk op het veld?","options":["9","10","11","12"],"answerIndex":2}', 'global'),
  (uuid_generate_v4(), 'quiz', 'sports', '{"question":"Welke afstand hoort bij een marathon?","options":["21,1 km","30 km","42,195 km","50 km"],"answerIndex":2}', 'global'),
  (uuid_generate_v4(), 'quiz', 'sports', '{"question":"Welke sport gebruikt een shuttle?","options":["Tennis","Badminton","Squash","Padel"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'sports', '{"question":"Wie won het WK voetbal in 2010?","options":["Nederland","Spanje","Duitsland","Italië"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'sports', '{"question":"Hoeveel sets moet je winnen in een grandslamfinale voor mannen?","options":["Best of 3","Best of 5","Eén set","Tot 21 punten"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'gaming', '{"question":"Welke studio maakte The Witcher 3?","options":["CD Projekt Red","BioWare","Ubisoft","Bethesda"],"answerIndex":0}', 'global'),
  (uuid_generate_v4(), 'quiz', 'gaming', '{"question":"Wat heb je nodig om een Nether-portaal in Minecraft te bouwen?","options":["Glas","Obsidiaan","Redstone","Quartz"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'gaming', '{"question":"In welke game hoor je de kreet \"Finish Him!\"?","options":["Street Fighter","Tekken","Mortal Kombat","Smash Bros"],"answerIndex":2}', 'global'),
  (uuid_generate_v4(), 'quiz', 'gaming', '{"question":"Welke console introduceerde de Mii-personages?","options":["PlayStation 3","Xbox 360","Nintendo Wii","GameCube"],"answerIndex":2}', 'global'),
  (uuid_generate_v4(), 'quiz', 'productivity', '{"question":"Welke methode deelt taken in urgent en belangrijk?","options":["Pomodoro","Eisenhower","Kanban","Scrum"],"answerIndex":1}', 'global'),
  (uuid_generate_v4(), 'quiz', 'productivity', '{"question":"Hoe lang duurt de lange pauze na vier pomodoro\'s?","options":["5 minuten","15 minuten","20 minuten","30 minuten"],"answerIndex":3}', 'global'),
  (uuid_generate_v4(), 'quiz', 'productivity', '{"question":"Welk toetsenbordcommando kopieert op een Mac?","options":["Cmd+C","Cmd+V","Cmd+X","Cmd+Z"],"answerIndex":0}', 'global'),
  (uuid_generate_v4(), 'quiz', 'productivity', '{"question":"Waar staat GTD voor?","options":["Getting Things Done","Great Time Deal","Good Task Dashboard","Goal Tracking Design"],"answerIndex":0}', 'global'),
  (uuid_generate_v4(), 'poll', 'general', '{"question":"Koffie of thee om te starten?","options":["Koffie","Thee"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'general', '{"question":"Boek of podcast in de avond?","options":["Boek","Podcast"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'general', '{"question":"Weekend: stad of natuur?","options":["Stad","Natuur"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'general', '{"question":"Nieuws checken in de ochtend of avond?","options":["Ochtend","Avond"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'general', '{"question":"Planner: digitaal of papier?","options":["Digitaal","Papier"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'sports', '{"question":"Hardlopen: ochtend of avond?","options":["Ochtend","Avond"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'sports', '{"question":"Workout vandaag: HIIT of steady state?","options":["HIIT","Steady state"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'sports', '{"question":"Speel je liever team- of solosport?","options":["Team","Solo"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'sports', '{"question":"Train jij met muziek of stilte?","options":["Muziek","Stilte"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'sports', '{"question":"Mobility vóór of na de training?","options":["Voor","Na"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'gaming', '{"question":"Console of pc vandaag?","options":["Console","PC"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'gaming', '{"question":"Campagne spelen: co-op of solo?","options":["Co-op","Solo"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'gaming', '{"question":"VR nu proberen of nog wachten?","options":["Proberen","Wachten"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'gaming', '{"question":"Games streamen of downloaden?","options":["Streamen","Downloaden"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'productivity', '{"question":"Start je dag met mail of focusblok?","options":["Mail","Focusblok"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'productivity', '{"question":"Taken tracken in Notion of Todoist?","options":["Notion","Todoist"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'productivity', '{"question":"Werk je liever thuis of op kantoor?","options":["Thuis","Kantoor"]}', 'global'),
  (uuid_generate_v4(), 'poll', 'productivity', '{"question":"Focusmuziek: lo-fi of stilte?","options":["Lo-fi","Stilte"]}', 'global')
on conflict do nothing;
